// src/Constants/ProductConstants.js

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE';
export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST';
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAILURE = 'PRODUCTS_DETAILS_FAILURE';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT'; // Add this line
// src/Constants/ProductConstants.js

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'; 
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'; 
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'; 
