// types.js

export const ALL_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const   ALL_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const   ALL_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';


export const PRODUCTS_DETAILS_REQUEST  = '   PRODUCTS_DETAILS_REQUEST '
export const   PRODUCTS_DETAILS_SUCCESS = '  PRODUCTS_DETAILS_SUCCESS'
export const   PRODUCTS_DETAILS_FAILURE = '  PRODUCTS_DETAILS_FAILURE'


export const   CLEAR_ERRORS = 'CLEAR ERRORS';


